# Model arguments
model_name_or_path: /home/sunl/ckpts/Qwen_Qwen2.5-Math-7B 
tokenizer_name_or_path: /home/sunl/ckpts/Qwen_Qwen2.5-Math-7B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
use_liger: false
bf16: true
tf32: true
output_dir: runs/bpo/bpo-qwen-2-5-7b-math-ep2-balance_hinge_alpha_0.3
# Dataset arguments
dataset_id_or_path: /home/sunl/app/sunl/llm_rl/data/orz_math

# LoRA arguments
use_peft: true
load_in_4bit: true
lora_target_modules: [ "q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
lora_r: 16
lora_alpha: 16

# Training arguments
beta: 0.1
max_length: 2048
max_prompt_length: 256
loss_type: balance_hinge_alpha
num_train_epochs: 2
per_device_train_batch_size: 1 
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-6 
lr_scheduler_type: constant
warmup_ratio: 0.03

# Logging arguments
logging_strategy: steps
logging_steps: 5
report_to:
- tensorboard
save_strategy: "steps" # "epoch"     
save_steps: 500
seed: 42

# Hugging Face Hub 
push_to_hub: False
  # hub_model_id: llama-3-1-8b-math-orca-qlora-10k-ep1 # if not defined same as output_dir
hub_strategy: every_save